### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by ezeamin** [Joselobo753/js-tp2-2-Rolingcode#6]
Ojo con la siguiente etiqueta que está mal la sintaxis:
```html
<meta author="Jose lobo" />
```

Y FALTA EL BODY!!!!!!1

**Comment by Joselobo753** [comment]
Por cosas como esas es mejor programar con un cafe y no terminar de programar para ir a buscar un cafe

**Comment by ezeamin** [comment]
Coincido
